--- #YAML:1.0
name:                Test-AbstractMethod
version:             0.01
abstract:            Make sure your abstract methods croaks like they should
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Claes Jakobsson <claesjac@cpan.org>
